spring:
  application:
    name: dabom

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

#  sql:
#    init:
#      mode: always
#      platform: mariadb
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql

  servlet:
    multipart:
      max-file-size: 100MB # 최대 파일 사이즈
      max-request-size: 100MB # 한 번 요청의 최대 사이즈

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        presigned-url-duration: ${S3_PRESIGNED_URL_DURATION}
        presigned-url-duration-img: ${S3_PRESIGNED_URL_IMG_DURATION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

file:
  upload:
    path: ${FILE_PATH}
    url: ${FILE_URL}
  ffmpeg:
    path: ${FFMPEG_PATH}
    hls:
      segment-duration: ${FFMPEG_SEGMENT_DURATION}

websocket:
  allowed-origin: ${SERVER}
